apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vcluster-manager-data
  namespace: vcluster-manager
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Mi
