//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgoCDSpec) DeepCopyInto(out *ArgoCDSpec) {
	*out = *in
	if in.RBACGroups != nil {
		in, out := &in.RBACGroups, &out.RBACGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgoCDSpec.
func (in *ArgoCDSpec) DeepCopy() *ArgoCDSpec {
	if in == nil {
		return nil
	}
	out := new(ArgoCDSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupOpsStatus) DeepCopyInto(out *BackupOpsStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupOpsStatus.
func (in *BackupOpsStatus) DeepCopy() *BackupOpsStatus {
	if in == nil {
		return nil
	}
	out := new(BackupOpsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeletionStatus) DeepCopyInto(out *DeletionStatus) {
	*out = *in
	if in.GracePeriodEndsAt != nil {
		in, out := &in.GracePeriodEndsAt, &out.GracePeriodEndsAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeletionStatus.
func (in *DeletionStatus) DeepCopy() *DeletionStatus {
	if in == nil {
		return nil
	}
	out := new(DeletionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FluxCDSpec) DeepCopyInto(out *FluxCDSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FluxCDSpec.
func (in *FluxCDSpec) DeepCopy() *FluxCDSpec {
	if in == nil {
		return nil
	}
	out := new(FluxCDSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LastBackup) DeepCopyInto(out *LastBackup) {
	*out = *in
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LastBackup.
func (in *LastBackup) DeepCopy() *LastBackup {
	if in == nil {
		return nil
	}
	out := new(LastBackup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotaSpec) DeepCopyInto(out *QuotaSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaSpec.
func (in *QuotaSpec) DeepCopy() *QuotaSpec {
	if in == nil {
		return nil
	}
	out := new(QuotaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RancherStatus) DeepCopyInto(out *RancherStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RancherStatus.
func (in *RancherStatus) DeepCopy() *RancherStatus {
	if in == nil {
		return nil
	}
	out := new(RancherStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceUsage) DeepCopyInto(out *ResourceUsage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceUsage.
func (in *ResourceUsage) DeepCopy() *ResourceUsage {
	if in == nil {
		return nil
	}
	out := new(ResourceUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreOpsStatus) DeepCopyInto(out *RestoreOpsStatus) {
	*out = *in
	if in.FirstTerminalAt != nil {
		in, out := &in.FirstTerminalAt, &out.FirstTerminalAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreOpsStatus.
func (in *RestoreOpsStatus) DeepCopy() *RestoreOpsStatus {
	if in == nil {
		return nil
	}
	out := new(RestoreOpsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VCluster) DeepCopyInto(out *VCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VCluster.
func (in *VCluster) DeepCopy() *VCluster {
	if in == nil {
		return nil
	}
	out := new(VCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VClusterList) DeepCopyInto(out *VClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VClusterList.
func (in *VClusterList) DeepCopy() *VClusterList {
	if in == nil {
		return nil
	}
	out := new(VClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VClusterSpec) DeepCopyInto(out *VClusterSpec) {
	*out = *in
	if in.ArgoCD != nil {
		in, out := &in.ArgoCD, &out.ArgoCD
		*out = new(ArgoCDSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Velero != nil {
		in, out := &in.Velero, &out.Velero
		*out = new(VeleroSpec)
		**out = **in
	}
	if in.Quotas != nil {
		in, out := &in.Quotas, &out.Quotas
		*out = new(QuotaSpec)
		**out = **in
	}
	if in.FluxCD != nil {
		in, out := &in.FluxCD, &out.FluxCD
		*out = new(FluxCDSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VClusterSpec.
func (in *VClusterSpec) DeepCopy() *VClusterSpec {
	if in == nil {
		return nil
	}
	out := new(VClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VClusterStatus) DeepCopyInto(out *VClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ResourceUsage != nil {
		in, out := &in.ResourceUsage, &out.ResourceUsage
		*out = new(ResourceUsage)
		**out = **in
	}
	if in.Rancher != nil {
		in, out := &in.Rancher, &out.Rancher
		*out = new(RancherStatus)
		**out = **in
	}
	if in.Vault != nil {
		in, out := &in.Vault, &out.Vault
		*out = new(VaultStatus)
		**out = **in
	}
	if in.LastBackup != nil {
		in, out := &in.LastBackup, &out.LastBackup
		*out = new(LastBackup)
		(*in).DeepCopyInto(*out)
	}
	if in.Deletion != nil {
		in, out := &in.Deletion, &out.Deletion
		*out = new(DeletionStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VClusterStatus.
func (in *VClusterStatus) DeepCopy() *VClusterStatus {
	if in == nil {
		return nil
	}
	out := new(VClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VClusterVeleroOps) DeepCopyInto(out *VClusterVeleroOps) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VClusterVeleroOps.
func (in *VClusterVeleroOps) DeepCopy() *VClusterVeleroOps {
	if in == nil {
		return nil
	}
	out := new(VClusterVeleroOps)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VClusterVeleroOps) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VClusterVeleroOpsList) DeepCopyInto(out *VClusterVeleroOpsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VClusterVeleroOps, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VClusterVeleroOpsList.
func (in *VClusterVeleroOpsList) DeepCopy() *VClusterVeleroOpsList {
	if in == nil {
		return nil
	}
	out := new(VClusterVeleroOpsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VClusterVeleroOpsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VClusterVeleroOpsStatus) DeepCopyInto(out *VClusterVeleroOpsStatus) {
	*out = *in
	out.Backup = in.Backup
	in.Restore.DeepCopyInto(&out.Restore)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VClusterVeleroOpsStatus.
func (in *VClusterVeleroOpsStatus) DeepCopy() *VClusterVeleroOpsStatus {
	if in == nil {
		return nil
	}
	out := new(VClusterVeleroOpsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultStatus) DeepCopyInto(out *VaultStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultStatus.
func (in *VaultStatus) DeepCopy() *VaultStatus {
	if in == nil {
		return nil
	}
	out := new(VaultStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VeleroSpec) DeepCopyInto(out *VeleroSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VeleroSpec.
func (in *VeleroSpec) DeepCopy() *VeleroSpec {
	if in == nil {
		return nil
	}
	out := new(VeleroSpec)
	in.DeepCopyInto(out)
	return out
}
