//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupOpsStatus) DeepCopyInto(out *BackupOpsStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupOpsStatus.
func (in *BackupOpsStatus) DeepCopy() *BackupOpsStatus {
	if in == nil {
		return nil
	}
	out := new(BackupOpsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreOpsStatus) DeepCopyInto(out *RestoreOpsStatus) {
	*out = *in
	if in.FirstTerminalAt != nil {
		in, out := &in.FirstTerminalAt, &out.FirstTerminalAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreOpsStatus.
func (in *RestoreOpsStatus) DeepCopy() *RestoreOpsStatus {
	if in == nil {
		return nil
	}
	out := new(RestoreOpsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VClusterVeleroOps) DeepCopyInto(out *VClusterVeleroOps) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VClusterVeleroOps.
func (in *VClusterVeleroOps) DeepCopy() *VClusterVeleroOps {
	if in == nil {
		return nil
	}
	out := new(VClusterVeleroOps)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VClusterVeleroOps) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VClusterVeleroOpsList) DeepCopyInto(out *VClusterVeleroOpsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VClusterVeleroOps, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VClusterVeleroOpsList.
func (in *VClusterVeleroOpsList) DeepCopy() *VClusterVeleroOpsList {
	if in == nil {
		return nil
	}
	out := new(VClusterVeleroOpsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VClusterVeleroOpsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VClusterVeleroOpsStatus) DeepCopyInto(out *VClusterVeleroOpsStatus) {
	*out = *in
	out.Backup = in.Backup
	in.Restore.DeepCopyInto(&out.Restore)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VClusterVeleroOpsStatus.
func (in *VClusterVeleroOpsStatus) DeepCopy() *VClusterVeleroOpsStatus {
	if in == nil {
		return nil
	}
	out := new(VClusterVeleroOpsStatus)
	in.DeepCopyInto(out)
	return out
}
